# docker/Dockerfile.nvidia
FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3 python3-pip ffmpeg git libsndfile1 \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && ln -s /usr/bin/pip3 /usr/bin/pip

WORKDIR /app
COPY .. /app

RUN pip install torch==2.3.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "-m", "src.pipeline"]